export const TYPE_NAMES = [
  'Bug',
  'Dark',
  'Dragon',
  'Electric',
  'Fairy',
  'Fighting',
  'Fire',
  'Flying',
  'Ghost',
  'Grass',
  'Ground',
  'Ice',
  'Normal',
  'Poison',
  'Psychic',
  'Rock',
  'Steel',
  'Stellar',
  'Water',
]

export const TYPE_SPRITE_ID: Record<string, number> = {
  Normal: 1,
  Fighting: 2,
  Flying: 3,
  Poison: 4,
  Ground: 5,
  Rock: 6,
  Bug: 7,
  Ghost: 8,
  Steel: 9,
  Fire: 10,
  Water: 11,
  Grass: 12,
  Electric: 13,
  Psychic: 14,
  Ice: 15,
  Dragon: 16,
  Dark: 17,
  Fairy: 18,
}

export const STATUS_VALUES = ['brn', 'par', 'psn', 'tox', 'slp', 'frz']
export const STATUS_LABELS: Record<string, string> = {
  brn: 'Burned',
  par: 'Paralyzed',
  psn: 'Poisoned',
  tox: 'Badly Poisoned',
  slp: 'Asleep',
  frz: 'Frozen',
}

// Items that boost a Pokémon's damage output (move-power multipliers and
// species-locked stat doublers). Megastones and utility items (Choice Scarf,
// Sitrus Berry, Assault Vest, Focus Sash, Leftovers, etc.) are omitted.
// Used to prefix the attacker's item in the calc-result title.
export const POWER_BOOSTING_ITEMS: ReadonlySet<string> = new Set([
  'Choice Band',
  'Choice Specs',
  'Light Ball',
  'Thick Club',
  'Deep Sea Tooth',
  'Life Orb',
  'Expert Belt',
  'Muscle Band',
  'Wise Glasses',
  'Punching Glove',
  'Loaded Dice',
  'Metronome',
  'Charcoal',
  'Mystic Water',
  'Miracle Seed',
  'Magnet',
  'Twisted Spoon',
  'Black Belt',
  'Black Glasses',
  'Sharp Beak',
  'Poison Barb',
  'Soft Sand',
  'Hard Stone',
  'Silver Powder',
  'Spell Tag',
  'Metal Coat',
  'Dragon Fang',
  'Never-Melt Ice',
  'Silk Scarf',
  'Sea Incense',
  'Wave Incense',
  'Rose Incense',
  'Odd Incense',
  'Rock Incense',
  'Soul Dew',
  'Adamant Orb',
  'Adamant Crystal',
  'Lustrous Orb',
  'Lustrous Globe',
  'Griseous Orb',
  'Griseous Core',
  'Draco Plate',
  'Dread Plate',
  'Earth Plate',
  'Fist Plate',
  'Flame Plate',
  'Icicle Plate',
  'Insect Plate',
  'Iron Plate',
  'Meadow Plate',
  'Mind Plate',
  'Pixie Plate',
  'Sky Plate',
  'Splash Plate',
  'Spooky Plate',
  'Stone Plate',
  'Toxic Plate',
  'Zap Plate',
])

// Items that boost a Pokémon's defensive outcome in the calc — flat damage
// reducers (Assault Vest), single-hit survivability (Focus Sash), and the
// type-resist berries (one-time half-damage on a super-effective hit).
// Used to prefix the defender's item in the calc-result title.
export const DEFENSE_BOOSTING_ITEMS: ReadonlySet<string> = new Set([
  'Assault Vest',
  'Focus Sash',
  'Babiri Berry',
  'Charti Berry',
  'Chilan Berry',
  'Chople Berry',
  'Coba Berry',
  'Colbur Berry',
  'Haban Berry',
  'Kasib Berry',
  'Kebia Berry',
  'Occa Berry',
  'Passho Berry',
  'Payapa Berry',
  'Rindo Berry',
  'Roseli Berry',
  'Shuca Berry',
  'Tanga Berry',
  'Wacan Berry',
  'Yache Berry',
])
